default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: ruby_basic_rest_development
# production:
#   primary: &primary_production
#     <<: *default
#     database: ruby_basic_rest_production
#     username: ruby_basic_rest
#     password: <%= ENV["RUBY_BASIC_REST_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: ruby_basic_rest_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: ruby_basic_rest_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: ruby_basic_rest_production_cable
#     migrations_paths: db/cable_migrate
